from .categorical_crossentropy import Loss_CategoricalCrossentropy
from .binary_crossentropy import Loss_BinaryCrossentropy
from .MSE import Loss_MeanSquaredError
from .MAE import Loss_MeanAbsoluteError